# Generated by Django 4.2.13 on 2024-07-24 20:50

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='figuredetail',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
