# Generated by Django 4.2.13 on 2024-07-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('figures', '0002_figuredetail_body_figuredetail_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
