# Generated by Django 4.2.14 on 2024-07-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0004_figuredetail_gallery_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='figuredetail',
            name='media_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
